<?php
/**
 * Plugin Name: %%APP_NAME%%
 * Description: Plugin generated by react-wp-scripts.
 */

namespace %%NAMESPACE%%;

require __DIR__ . '/loader.php';

add_action( 'wp_enqueue_scripts', __NAMESPACE__ . '\\enqueue_assets' );

function enqueue_assets() {
	// https://github.com/humanmade/react-wp-scripts#enqueue_assets
	// Add additional options here:
	$options = [];

	Loader\enqueue_assets( plugin_dir_path( __FILE__ ), $options );
}
